---
- hosts: g-pool
  vars:
  vars_files:
    - vars/vars.yml
  remote_user: centos
  become: yes
  tasks:
  - name: pgpool stop
    shell: "/usr/pgpool-{{pgver}}/bin/pgpool -m immediate stop"
    become_user: root
    ignore_errors: yes
  - name: vip release 1
    shell: "/usr/pgpool-{{pgver}}/bin/ifupdown.sh down {{if_cmd_param1}}"
    become_user: root
    ignore_errors: yes
  - name: vip release 2
    shell: "/usr/pgpool-{{pgver}}/bin/ifupdown.sh down {{if_cmd_param2}}"
    become_user: root
    ignore_errors: yes
  - name: delete pgpool_status
    file:
      path: "/tmp/pgpool_status"
      state: absent
  - name: delete socket file WD9000
    file:
      path: "/tmp/.s.PGPOOLWD_CMD.9000"
      state: absent
  - name: delete socket file PGSQL.5432
    file:
      path: "/tmp/.s.PGSQL.5432"
      state: absent
  - name: delete socket file PGSQL.9898
    file:
      path: "/tmp/.s.PGSQL.9898"
      state: absent



